source 'https://rubygems.org'
ruby '2.1.5'

gem 'activesupport'
gem 'puma'
gem 'rack-google-analytics'
gem 'rake'
gem 'resque' , '~> 1.25.2'
gem 'resque-scheduler', '~> 4.0'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'twitter'